### ISSUE TITLE
[MacOS] Vesktop not asking for microphone permission

### ISSUE THREAD

**Issue by Lenochxd** [Vencord/Vesktop#440] opened 2024-03-12 21:20 UTC
**Describe the bug**

Vesktop does not ask for microphone permission (Hackintosh MacOS Sonoma 14.3.1)

**To Reproduce**

1. install macos Sonoma
2. join vc
3. mic not working

**Expected behavior**

Vesktop should ask for mic permission, it already asks for screen sharing before streaming, but we cannot 

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/101269524/f92da4fe-0d8c-4daf-99fa-5ea8e289285f)

**Desktop (please complete the following information):**
 - OS/Distro: MacOS (Hackintosh)
 - Version: Sonoma 14.3.1

**Command line output**

```
j@Mac-Pro Vencord-client % open /Applications/Vesktop.app
j@Mac-Pro Vencord-client %
```
*(sorry :/  )*

**Additional context**

I installed Vesktop because original Discord doesn't let me stream without crashing (hackintosh issue), and now I can stream but not talk.

Also, I tried giving microphone permissions to dev.vencord.vesktop manually but that doesn't seem possible anymore on Sonoma.

**Comment by Lenochxd** [comment] 2024-03-12 21:28
**Update!**

I tried downgrading to 1.5.0 because I saw that 1.5.1 fixed screenshare audio using microphone on debian, and this time the permission was asked when opening the app

![image](https://github.com/Vencord/Vesktop/assets/101269524/edd31aa8-f256-45c3-8ae6-2522c592fc58)

**Comment by tworstwots** [comment] 2024-03-13 04:52
Can confirm, this is broken for me on 1.5.1 as well.

**Comment by mymindishazel** [comment] 2024-03-13 06:11
> Also, I tried giving microphone permissions to dev.vencord.vesktop manually but that doesn't seem possible anymore on Sonoma.

there’s always the cursed way

`sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db`

`insert into access values ('kTCCServiceMicrophone','dev.vencord.vesktop', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1706117326, null, null, 'UNUSED', 0);`

**Comment by Vendicated** [comment] 2024-03-13 06:19
might be because vesktop 1.5.1 is now signed (should be? im not actually entirely sure)

and possibly missing some entitlements?

**Comment by SympathyTea** [comment] 2024-03-16 18:02
also having this same issue with 1.5.1 on windows 11 (if it matters to mention)

**Comment by Un1q32** [comment] 2024-03-16 21:05
same issue on 1.5.1 macOS 14.4
MBP mid 2014 running OCLP

**Comment by Un1q32** [comment] 2024-03-16 21:06
> there’s always the cursed way
> 
> `sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db`
> 
> `insert into access values ('kTCCServiceMicrophone','dev.vencord.vesktop', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1706117326, null, null, 'UNUSED', 0);`

This worked for me as a workaround

**Comment by MrGamerDoesGames** [comment] 2024-03-19 01:18
> > Also, I tried giving microphone permissions to dev.vencord.vesktop manually but that doesn't seem possible anymore on Sonoma.
> 
> there’s always the cursed way
> 
> `sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db`
> 
> `insert into access values ('kTCCServiceMicrophone','dev.vencord.vesktop', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1706117326, null, null, 'UNUSED', 0);`

how did you run this in terminal? I tried and just got a prompt asking me to put text in

**Comment by SpektacleFR** [comment] 2024-03-22 12:25
> > Also, I tried giving microphone permissions to dev.vencord.vesktop manually but that doesn't seem possible anymore on Sonoma.
> 
> there’s always the cursed way
> 
> `sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db`
> 
> `insert into access values ('kTCCServiceMicrophone','dev.vencord.vesktop', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1706117326, null, null, 'UNUSED', 0);`

Getting this error when putting the second line into the sqlite prompt:
```
Runtime error: UNIQUE constraint failed: access.service, access.client, access.client_type, access.indirect_object_identifier (19)
```
Any help is appreciated.

**Comment by andresik12** [comment] 2024-03-22 14:42
Same error on 1.5.1 (1.5.0 is ok), but when i try enter an voice channel or open audio settings, client crashing. attaching the log: [crash.log](https://github.com/Vencord/Vesktop/files/14724126/crash.log)

**Comment by AvianAnalyst** [comment] 2024-03-24 06:47
@MrGamerDoesGames That prompt is the sqlite prompt (i assume) and is where you put in the next provided input 

@SpektacleFR The problem is there's already a permissions entry. I'm not sure why it wasn't working for us, but you have to delete it first. Then you can insert the new permissions line with the command provided, restart vesktop, and it should work for you (did for me at least). 

To delete the previous one I used 
`delete from access where service='kTCCServiceMicrophone' and client='dev.vencord.vesktop';` but if you know sql and have a different/better way that shouldn't be fine.

**Comment by ayildirim21** [comment] 2024-03-28 05:24
Having this same issue on arch linux. Permanently muted, and no input device is being detected in the settings

**Comment by archaicimaging** [comment] 2024-03-28 11:46
Had this issue on MacOS Ventura 13.6.6, on Canary Vesktop as well. Trying to enter the Voice And Video setting page, joining VCs, both immediately crashed the app.

**Comment by AvianAnalyst** [comment] 2024-03-28 22:49
I don't know if it's related, but on mac I'm not able to screenshare anymore because of permissions problems.

**Comment by EndenDragon** [comment] 2024-03-29 06:56
> might be because vesktop 1.5.1 is now signed (should be? im not actually entirely sure)
> 
> and possibly missing some entitlements?

After reading up the termination reason provided in #475, could the solution be something along the lines described within this? https://github.com/electron-userland/electron-builder/issues/6948#issuecomment-1169673740

**Comment by lockieluke** [comment] 2024-04-10 16:03
> > Also, I tried giving microphone permissions to dev.vencord.vesktop manually but that doesn't seem possible anymore on Sonoma.
> 
> there’s always the cursed way
> 
> `sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db`
> 
> `insert into access values ('kTCCServiceMicrophone','dev.vencord.vesktop', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1706117326, null, null, 'UNUSED', 0);`

No permission
![image](https://github.com/Vencord/Vesktop/assets/25424409/8e864e89-66ee-4016-85be-a8cce1ec8b32)

**Comment by lockieluke** [comment] 2024-04-10 17:06
![Screenshot 2024-04-10 at 18 05 49](https://github.com/Vencord/Vesktop/assets/25424409/f89b7072-f330-4a72-9fbc-d671c71d3cfa)

Still doesn't work

**Comment by EndenDragon** [comment] 2024-04-10 17:12
> ![Screenshot 2024-04-10 at 18 05 49](https://private-user-images.githubusercontent.com/25424409/321333285-f89b7072-f330-4a72-9fbc-d671c71d3cfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjkzOTAsIm5iZiI6MTcxMjc2OTA5MCwicGF0aCI6Ii8yNTQyNDQwOS8zMjEzMzMyODUtZjg5YjcwNzItZjMzMC00YTcyLTlmYmMtZDY3MWM3MWQzY2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE3MTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzFiNWVjNzA0NDY3ODc0MmFlMTFmZjkxZmE4OTA1MDlmMTQ2ZWY4ZjNmNTkyMzZiMjRmOWIxY2U3NGFlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SQJindRct213T5SPvR4vHdLCd8T3LJGs3EIARpmA6Yk)
> 
> Still doesn't work

Please reference this comment for solution: https://github.com/Vencord/Vesktop/issues/440#issuecomment-2016713302

**Comment by archaicimaging** [comment] 2024-04-15 10:24
Do we have a official fix for this yet, or are we still using the workaround?

**Comment by Lenochxd** [comment] 2024-04-15 11:08
> Do we have a official fix for this yet, or are we still using the workaround?

You can downgrade to [1.5.0](https://github.com/Vencord/Vesktop/releases/tag/v1.5.0)

**Comment by archaicimaging** [comment] 2024-04-15 12:34
Alright, I can confirm it indeed works via downgrading to 1.5.0, I've been in a VC for 15 minutes and it's just fine.

**Comment by Vendicated** [comment] 2024-04-16 22:19
there's no fix. Like i said, it's likely due to missing entitlements in the plist which is required when signing your app

i don't have a mac nor do i know anything about mac so i personally can't fix it. contributions welcome

see https://github.com/electron-userland/electron-builder/issues/6948#issuecomment-1169673740

**Comment by ssalggnikool** [comment] 2024-04-22 03:19
I have attempted to fix the issue here by adding the entitlements by file in my pull request here https://github.com/Vencord/Vesktop/pull/533

**Comment by Vendicated** [comment] 2024-04-26 19:49
please try the builds from https://github.com/Vencord/Vesktop/releases/v1.5.2-alpha.1 and see if all permissions work correctly now

**Comment by lockieluke** [comment] 2024-04-26 19:56
I manually removed the microphone permission entry from System Settings using a SQL Viewer and I can confirm the new build now works as expected
![image](https://github.com/Vencord/Vesktop/assets/25424409/acb4648b-87a7-4a98-9a17-7b9e4927ab3b)

**Closed** 2024-04-26 20:09 UTC
Labels: bug, help wanted
