### ISSUE TITLE
Wayland scaling on Gnome is broken

### ISSUE THREAD

**Issue by Sinestia** [Vencord/Vesktop#338] opened 2024-01-16 12:14 UTC
**Describe the bug**
When running vesktop on Gnome on Arch Linux and scaling set to 2x, it looks fine running in xwayland mode. However, the performance is poor so even when running default Discord I force it to Wayland with
`--enable-features=UseOzonePlatform --ozone-platform=wayland`

With vesktop however, it does not scale properly when Wayland is enabled, looking blurry. This works on the default discord client. 

One can throw in --force-device-scale-factor=2 which makes it scale correctly but breaks the window. 

This works correctly if Gnome is restarted with experimental fractional scaling enabled, but that has its own separate issues so if a more general fix could be found it would be ideal. 

The terminal does produce a specific error with those flags, which seems relevant.

`[106432:0116/061246.706670:ERROR:browser_main_loop.cc(276)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

**To Reproduce**
Run Vesktop on Wayland's GNOME, with integer scaling, with:

`vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Expected behavior**
The window should open, running Wayland, and scaled properly 2x. 

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/40812746/c04f3cbd-f1bb-4819-b76b-38394c6463f7)
Terminal for comparison purposes. 

![Screenshot from 2024-01-16 06-07-32](https://github.com/Vencord/Vesktop/assets/40812746/159d8475-a411-46e1-b0ac-af151cc87a0b)
With --force-device-scale-factor set. 

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): Gnome
 - Version: Gnome 45, Vesktop 4.5. 

**Additional context**
n/a

**Comment by Vendicated** [comment] 2024-01-16 14:04
try building from source with older / newer (alpha) electron versions and see if its fixed

nothing on our end, simply an issue with electron

**Comment by Sinestia** [comment] 2024-01-16 15:51
That works for now, thank you very much. 

For anyone reading, newer electron, 29 alpha, did not work.

However, 24.8.8, changed within package.json, did work.

**Comment by Vendicated** [comment] 2024-01-16 15:52
holy shit why so old, try 27/26

**Comment by Vendicated** [comment] 2024-01-16 15:52
closing because there's nothing we can do. you should try to create a minimal reproduction example electron app and report it to electron

**Closed by Vendicated** 2024-01-16 15:52 UTC
Labels: bug, wontfix, blocked:upstream

**Comment by Sinestia** [comment] 2024-01-16 16:00
> holy shit why so old, try 27/26

Believe it or not, I did. It seems that 24 is the newest that works unfortunately.

**Comment by tschai-yim** [comment] 2024-02-14 13:40
Normally this can be fixed by passing in `--disable-features=WaylandFractionalScaleV1` but this isn't the case for Vesktop. In VSCode this was [apparently also the case](https://github.com/microsoft/vscode/issues/192590#issuecomment-1713604453) because they maintained their own disabled features lists.

**Comment by tschai-yim** [comment] 2024-02-14 14:01
From [the actual upstream issue](https://issues.chromium.org/issues/40236124) you can do:
```sh
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
# or
dconf write /org/gnome/mutter/experimental-features "['scale-monitor-framebuffer']"
```
This fixes all chromium apps but again because it's experimental others (like JetBrains products) blurry.
