### ISSUE TITLE
Vesktop stops responding after selecting a screen source and starts loading audio sources.

### ISSUE THREAD

**Issue by imnotliveyet** [Vencord/Vesktop#521] opened 2024-04-19 03:30 UTC
Vesktop stops responding after selecting a screen source and starts loading audio sources.

**To Reproduce**

Install Linux Mint
Install Vesktop from .deb
Follow steps at the top of [this](https://gist.github.com/Vendicated/b655044ffbb16b2716095a448c6d827a) under Ubuntu
See that you need pipewire
Follow [this](https://www.baeldung.com/linux/pulseaudio-pipewire-replace) guide
Restart PC
Set audio sources in sound preferences app
Open Vesktop, join a VC
Click "Share your Screen"
Select any source <-- This is when it stops responding, ignoring mouse inputs and requiring an app restart.

**Expected behavior**

Audio sources load, allowing me to screenshare with audio.

**Desktop:**

 - OS/Distro: Linux Mint
 - Desktop Environment (linux only): MATE
 - Version: 21.3

**Comment by Curve** [comment] 2024-04-19 08:55
What Vesktop version are you using? Can you please also provide console output + Venmic logs? (See here: https://github.com/Vencord/venmic?tab=readme-ov-file#-debugging)

**Comment by Vendicated** [comment] 2024-04-19 11:30
duplicate of multiple other issues

already fixed, but not released yet (will be very soon)

**Closed by Vendicated** 2024-04-19 11:30 UTC
Labels: bug
