### ISSUE TITLE
Segfault immediately after startup (Arch Linux)

### ISSUE THREAD

**Issue by RolesG** [Vencord/Vesktop#524] opened 2024-04-20 08:46 UTC
**Describe the bug**

Vesktop opens, displays the discord loading screen briefly, then closes. 

**To Reproduce**

Run Vesktop

**Expected behavior**

Vesktop functions

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: Garuda Linux
 - Desktop Environment: KDE Plasma 6.0.4 (Wayland)
 - Version: N/A (Just updated today)
 
 

**Command line output**

```
MESA-INTEL: warning: cannot initialize blitter engine
[arRPC > ipc] not available, trying again (attempt 1)
[arRPC > ipc] listening at /run/user/1000/discord-ipc-1
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
[43893:0420/013649.091731:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[43893:0420/013649.092615:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[43893:0100/000000.566331:ERROR:broker_posix.cc(41)] Recvmsg error: Connection reset by peer (104)
Segmentation fault (core dumped)

```

**Additional context**

I suspect it has to do with the blitter engine error, but I have no idea what it means. Googling didn't help in this case. I have an intel gpu (Arc A770).

**Comment by RolesG** [comment] 2024-04-20 08:48
Alrighty. Will do.

**Comment by RolesG** [comment] 2024-04-20 08:50
> Electron 30 issue use 29. Report this to the Aur maintainer.

I have Electron 29 installed. How do I launch Vesktop with a specific Electron version?

**Comment by Vendicated** [comment] 2024-04-20 09:14
duplicate of several other issues.

**Closed by Vendicated** 2024-04-20 09:14 UTC
Labels: bug
