### ISSUE TITLE
"Enable Spellcheck" option has disappeared

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#434] opened 2024-03-11 15:34 UTC
![image](https://github.com/Vencord/Vesktop/assets/30274161/a8e40443-b1f8-4ea3-a41c-ac64baad0426)

It was there before.

**Comment by Vendicated** [comment] 2024-03-12 00:38
this was caused by a breaking change to the context menu API provided by Vencord itself. We simply forgot to update Vesktop.

fixed via https://github.com/Vencord/Vesktop/commit/738fa588a606bb6ebddca1187a0c94152707c62e

**Closed by Vendicated** 2024-03-12 00:38 UTC
Labels: bug

**Comment by EthanDunning** [comment] 2025-07-25 22:05
This problem appears to be happening again now.
