### ISSUE TITLE
[Capture Card Absence] Vencord Capture Card Not Available

### ISSUE THREAD

**Issue by JJDizz1L** [Vencord/Vesktop#678] opened 2024-06-19 21:27 UTC
### Discord Account

dizziee

### Operating System

Windows 11 23H2

### What happens when the bug or crash occurs?

Every single time I try to share my capture card.
![image](https://github.com/Vencord/Vesktop/assets/37751357/3a4aba66-9e37-42d3-8fd7-e22138116c20)
![image](https://github.com/Vencord/Vesktop/assets/37751357/154ae5e8-d6eb-4e93-a2ff-426044383068)

### What is the expected behaviour?

I expected Vencord to be able to share my capture card as native discord, but it isn't an option.

### How do you recreate this bug or crash?

1. I join a voice chat. 2. I click the stream or share screen button. 3. I do not see the option to use my capture device.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-06-23 15:05
duplicate of https://github.com/Vencord/Vesktop/issues/302

**Closed by Vendicated** 2024-06-23 15:05 UTC
Labels: bug
