### ISSUE TITLE
Crashes immediately after joining a voice channel

### ISSUE THREAD

**Issue by EndenDragon** [Vencord/Vesktop#470] opened 2024-03-27 08:33 UTC
**Describe the bug**
I am unable to join voice channels. The desktop app immediately crashes.

**To Reproduce**
1. Join a server voice channel
2. The app crashes

**Expected behavior**
Being able to participate in the voice channel as usual.

**Screenshots**
<img width="1112" alt="image" src="https://github.com/Vencord/Vesktop/assets/16626766/24262061-75ee-4589-8ad1-92b817219a7e">

**Desktop (please complete the following information):**
 - OS/Distro: [e.g. Windows / Fedora Linux / MacOs] MacOS
 - Desktop Environment (linux only): [e.g. gnome, kde, sway]
 - Version: [e.g. 22] 10.15.7

**Command line output**

The following stack trace is provided after Vesktop app crashes
https://pastebin.com/mkBGyiHs

**Additional context**
N/A

**Comment by Vendicated** [comment] 2024-03-27 13:28
duplicate of #440

**Closed by Vendicated** 2024-03-27 13:28 UTC
Labels: bug
