### ISSUE TITLE
[Feature Request] Smooth Scrolling!

### ISSUE THREAD

**Issue by TheRealFame** [Vencord/Vesktop#1002] opened 2024-12-12 20:35 UTC
### Motivation

I was hoping to type this up real quickly, So. Base chromium has features to use smooth scrolling with any app toggling the flag itself, So I was thinking maybe a toggle in vesktop itself would be possible to add.

### Solution

Have electron launch with smooth scrolling enabled for the client! Or make it a toggle that turns on next launch and every launch after.

### Alternatives

Just, Not add the change. 

But i was really hoping to be able to get through my lists of servers and messages faster by having this windows feature back on discord for linux!

### Additional context

Middle click on your web browser. (For most this is already enabled.)

And move your cursor downwards while keeping your middle click held down. That would quickly make you scroll down.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment] 2024-12-12 21:05
middle click scroll and smooth scrolling are two different things

duplicate of https://github.com/Vencord/Vesktop/issues/171

**Closed by Vendicated** 2024-12-12 21:05 UTC
Labels: enhancement

**Comment by TheRealFame** [comment] 2024-12-12 22:52
> middle click scroll and smooth scrolling are two different things
> 
> duplicate of https://github.com/Vencord/Vesktop/issues/171

so it's coming natively on the next update 🤔

**Comment by Vendicated** [comment] 2024-12-13 06:05
no. you can enable it with the command line flag

**Comment by TheRealFame** [comment] 2024-12-14 01:18
> no. you can enable it with the command line flag

I'm on kde plasma, How do I do that?

**Comment by TheRealFame** [comment] 2024-12-21 04:45
Any Response? 

@Vendicated

**Comment by Vendicated** [comment] 2024-12-21 11:02
Read the issue I linked and you will know
