### ISSUE TITLE
[Bug] Cannot screenshare

### ISSUE THREAD

**Issue by duckydee** [Vencord/Vesktop#618] opened 2024-05-23 19:29 UTC
### Discord Account

duckydee

### Operating System

Windows 10

### What happens when the bug or crash occurs?

I attempt to screenshare, and nothing happens when I confirm in the menus.

### What is the expected behaviour?

It should start sharing my screen.

### How do you recreate this bug or crash?

1. click screenshare button
2. select window to screenshare
3. quality and framerate doesnt matter
4. click go live
5. menu closes, but no screenshare occurs

### Debug Logs

```
Error during screenshare picker Aborted
(node:8292) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:24:2653)
(Use `Vesktop --trace-warnings ...` to show where the warning was created)
(node:8292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

### Request Agreement

- [x] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-05-24 00:50
to be able to look into this issue, we need more info

try screensharing in your web browser by visiting discord.com/app. if that also doesn't work, then it's an issue with your system so you'll have to figure it out yourself (e.g. update gpu drivers)

other than that, any more info you could share that you think might be relevant might be useful! a screen recording of you going through this process and running into the issue would also help

**Comment by duckydee** [comment] 2024-05-24 00:57
I don't think it's a system issue, since I can use the actual discord app (even with vencord installed on it) and screenshares will work just fine. 

demo vid: Left is vesktop, right is discord
https://github.com/Vencord/Vesktop/assets/31322692/62a255ff-b4a8-4e93-96b6-9487db11f42e

Besides this, what can I provide to give more info? Running from a command prompt really doesn't give me that much information, as no info gets printed specifically when i click screenshare, the debug logs I posted were just the last thing it put out.

**Comment by Vendicated** [comment] 2024-05-24 01:40
check errors inside the chrome console (ctrl shift i)

**Comment by duckydee** [comment] 2024-05-28 16:22
![image](https://github.com/Vencord/Vesktop/assets/31322692/514f761e-8c44-4fcd-9098-b52b8a875f1e)

Gotcha! This message shows up in the console when I attempt to screenshare.

**Comment by Lythium4848** [comment] 2024-06-10 19:23
Getting the same errors on Fedora 40 running with KDE Plasma 6 on Wayland except the error is happening when i click on the screen share button to open the modal.

**Comment by Vendicated** [comment] 2024-06-10 19:41
@Lythium4848 that's an issue with your system and has nothing to do with this issue, nor is something vesktop can fix. look at other issues specific to kde

**Comment by duckydee** [comment] 2024-06-11 03:33
> > ![image](https://private-user-images.githubusercontent.com/31322692/334494857-514f761e-8c44-4fcd-9098-b52b8a875f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDg2NjUsIm5iZiI6MTcxODA0ODM2NSwicGF0aCI6Ii8zMTMyMjY5Mi8zMzQ0OTQ4NTctNTE0Zjc2MWUtOGM0NC00ZmNkLTkwOTgtYjUyYjhhODc1ZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE5MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YWEwMzg1ZGU0NjBjYTljNTc0MTEyYTc5Zjk2MTY4YzlkYTM1ODRlNGI4Yzc0Njg3MmI4NjQ5MGUwYWQ2OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pJxRoKcwXqV8TuIkADJhjtJP21Sx62Gwu0LhA1xnQiQ)
> > Gotcha! This message shows up in the console when I attempt to screenshare.
> 
> from your error, it seems like you chose to share with audio. does it work if you share without it?

Audio definitely seems to be the issue: Vesktop screenshares without audio do indeed work. It's not just a Vesktop thing by the way, it's also on ArmCord I've noticed similar problems. What similarities between two completely seperate modded clients would cause such a bug?

**Comment by PolisanTheEasyNick** [comment] 2024-06-11 07:14
> What similarities between two completely seperate modded clients would cause such a bug?

Chromium or pulseaudio/pipewire. Can you please specify which sound server you are using? If pipewire, do you have pipewire-pulse installed?

**Comment by Vendicated** [comment] 2024-06-11 11:14
duplicate of #334 then. it's probably an electron issue because it used to work and broke even though we changed nothing, and you claim it happens on armcord too

but not sure, i'll have to investigate and see if I can reproduce

**Closed by Vendicated** 2024-06-11 11:14 UTC
Labels: bug

**Comment by Akirapearl** [comment] 2024-06-20 21:08
Hi, had the same issue as top commenter, yet it doesn't matter how do i try to screenshare, or what, i tried file manager, browser, entire screen...I'm on PopOS 22.04 and i did recently update my system, just yesterday was able to do the same thing with success so far.

I'm running the flatpak version and I am aware that most updates claimed by Vesktop might not be applying since the "New Update" top right windows keeps poping up, just saying this for context.

Can i provide any meaningful log to check on this? if so, where should i look for those logs?

**Comment by Vendicated** [comment] 2024-06-20 21:26
please do not hijack resolved issues. this is a windows specific issue and has nothing to do with your problem. it's an issue with your system. try using non-flatpak
