### ISSUE TITLE
[Bug] <The Vencord settings are missing!>

### ISSUE THREAD

**Issue by sylvi-3** [Vencord/Vesktop#573] opened 2024-05-03 17:15 UTC
### Discord Account

sy1vi3_

### Operating System

NixOS 24.05

### Linux Only ~ Desktop Environment

Hyprland (Wayland)

### What happens when the bug or crash occurs?

I can't find the plugin settings. This might just be me being silly, but I can't for the life of me figure out where to change my plugins! It used to be that there would be options in settings for `Vencord` and `Plugins`, but they don't seem to be there anymore.

### What is the expected behaviour?

Vencord settings/plugin settings should be visible in the Discord settings menu

### How do you recreate this bug or crash?

1. Use Vesktop V1.5.1
2. Look for the Vencord Settings
3. Discover that you can only see the default discord settings!

### Image
![20240503-1317-screenie](https://github.com/Vencord/Vesktop/assets/167730518/d8a1948a-f3e0-4c8d-83df-4a4c61041f36)

### Debug Logs

```
There is no crash log for this I'm afraid.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by sunnniee** [comment] 2024-05-03 17:22
> [x] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-05-03 17:48
duplicate of more than 5 other issues. please check existing issues properly next time!

**Closed by Vendicated** 2024-05-03 17:48 UTC
Labels: bug
