### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by Parilia** [Vencord/Vesktop#519] opened 2024-04-18 18:19 UTC
When prompted to update the button will make my screen go blank, I checked settings and I see no vesktop setting, it is as if im using stock discord. My theme is still in place though nd pinned DM's so the plugins still seem active.  
I am using the RPM.

**Screenshots**

![Screenshot_18-04-2024_19:09](https://github.com/Vencord/Vesktop/assets/22579268/06520dbe-9ef3-47f3-b1c3-403464fb108b)
![Screenshot_18-04-2024_19:10](https://github.com/Vencord/Vesktop/assets/22579268/81579b6e-031c-4351-a0e2-3c2e6ad91c76)

**Desktop**
 - OS/Distro: Nobara Linux 39
 - Desktop Environment (linux only): kde 6.0.3

**Command line output**

```
[[38;2;88;101;242marRPC[0m > [38;2;254;231;92mipc[0m] listening at /run/user/1000/discord-ipc-0
[[38;2;88;101;242marRPC[0m > [38;2;235;69;158mwebsocket[0m] listening on 6463
[[38;2;88;101;242marRPC[0m > [38;2;237;66;69mprocess[0m] started
```

**Additional context**

**Comment by Vendicated** [comment] 2024-04-18 19:06
do not comment "same issue", it is just spam. reactions exist for a reason

duplicate of #516

**Closed by Vendicated** 2024-04-18 19:06 UTC
Labels: bug
