### ISSUE TITLE
Restarting app automatically mutes my microphone

### ISSUE THREAD

**Issue by bl4xe** [Vencord/Vesktop#145] opened 2023-10-12 16:36 UTC
Whenever I restart the App, I get muted for some reason and always have to unmute myself again

**Comment by bl4xe** [comment] 2023-10-12 16:42
> This may be related to spotify

I do not use Spotify, could it be some other program that I'm using?

**Comment by Vendicated** [comment] 2023-10-13 02:19
i can reproduce. it's probably a discord web thing because of permissions

**Comment by ArjixWasTaken** [comment] 2023-11-18 18:05
.

**Comment by kaitlynkittyy** [comment] 2024-05-03 02:37
> i can reproduce. it's probably a discord web thing because of permissions

this is what happens to me too, but it automatically unmutes upon joining a call, so is this something that was fixed, or is it in need of more research?

**Comment by PolisanTheEasyNick** [comment] 2024-05-03 11:19
We can use Flux event `RTC_CONNECTION_STATE` and check for params.state to be `RTC_CONNECTED`. It will mean that user connected to some call. Then we can see whether we are selfMuted and if so then toggleSelfMute.

**Comment by Vendicated** [comment] 2024-05-03 12:19
> this is what happens to me too, but it automatically unmutes upon joining a call

same here, so i'll be closing this as resolved

**Closed by Vendicated** 2024-05-03 12:19 UTC
Labels: bug
