### ISSUE TITLE
[Bug] When capturing a specific window instead of a full monitor/desktop, resizing the window will freeze the screen-share

### ISSUE THREAD

**Issue by HiroseKoichi** [Vencord/Vesktop#312] opened 2023-12-29 08:42 UTC
If you resize a captured window, it will freeze the screen-share, but audio still plays. However, this only happens when using the "windows" option in the screen-share; capturing a full monitor/desktop does not freeze the screen-share when resizing a window.

![example](https://github.com/Vencord/Vesktop/assets/86906598/b6dc3dc8-fe52-46ca-b430-002a8c63acb6)

There's an open issue on [discord-screenaudio](https://github.com/maltejur/discord-screenaudio/) as well, which I assume your implementation is based on since it mentions it in their readme: https://github.com/maltejur/discord-screenaudio/issues/220

Stable 256231 (96a39c5)
Vencord 6bbf562 (Vesktop V0.4.4)
Electron 27.1.3
Chromium 118.0.5993.159
NixOS 23.11
Kernel: 6.1.68
DE: Plasma 5.27.10 (Wayland)
WM: kwin

**Comment by Vendicated** [comment] 2024-01-06 01:25
can't reproduce on gnome. likely an issue with plasma, as also mentioned by malte in the linked issue

try on a different DE/WM

since this issue is out of our control and there's nothing we can do, i'll close this as wontfix. screenshare is controlled by chromium & your desktop environment, not us

**Closed by Vendicated** 2024-01-06 01:25 UTC
