### ISSUE TITLE
The volume of the microphone in the system changes itself.

### ISSUE THREAD

**Issue by VolRen-ShYK** [Vencord/Vesktop#460] opened 2024-03-18 14:43 UTC
Describe the bug: The microphone volume changes on its own.

To Reproduce: You have to speak loudly to decrease the microphone volume or say nothing at all to increase it.

Expected behavior: I would like the volume not to change as it is done for example in Webcord.

 - OS/Distro: Linux EndeavourOS
 - Desktop Environment: KDE Plasma 6
 - Version Vesktop: 1.5.1

**Comment by Vendicated** [comment] 2024-03-18 14:52
duplicate of https://github.com/Vencord/Vesktop/issues/161

**Closed by Vendicated** 2024-03-18 14:52 UTC
Labels: bug
