### ISSUE TITLE
[Bug] Voice message plugin uses system selected microphone instead of discord selected

### ISSUE THREAD

**Issue by mhkdepauw** [Vencord/Vesktop#662] opened 2024-06-15 14:41 UTC
### Operating System

Fedora 39

### Linux Only ~ Desktop Environment

Gnome on Wayland

### What happens when the bug or crash occurs?

If you record a voice message with the voice message for desktop plugin, it will record with the microphone that is selected in your system settings instead of the one that you have selected in Discord.

### What is the expected behaviour?

Recording voice messages should always happen with the microphone selected in discord.

### How do you recreate this bug or crash?

1. set microphone in discord and system settings to differen things
2. record a voice message in discord
3. observe that it uses the system settings set microphone.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-06-15 14:45
duplicate of Vendicated/Vencord#2477

![Screenshot_2024-06-15-16-45-02-31_4d38fce200f96aeac5e860e739312e76](https://github.com/Vencord/Vesktop/assets/45497981/3ef1d104-8e6d-459b-9574-f459391f9975)

**Closed by Vendicated** 2024-06-15 14:45 UTC
Labels: bug

**Comment by mhkdepauw** [comment] 2024-06-16 14:45
My bad
