### ISSUE TITLE
Autostart JavaScript Error in Linux

### ISSUE THREAD

**Issue by CelalCaglarOzturk** [Vencord/Vesktop#286] opened 2023-12-12 11:00 UTC
I installed Vesktop from Flatpak,
Autostart option enabled when first start,
Application doesnt even start after restart so i added the app to autostart manually,
Then every restart it throw this error: 
![resim](https://github.com/Vencord/Vesktop/assets/59174596/241e0d08-699e-4d19-9916-ec225938a154)
Ctrl+R doesn't work in this window, 
after hitting OK from error VC symbol comes and Vesktop Stuck in this animation
![resim](https://github.com/Vencord/Vesktop/assets/59174596/2e5ebbce-73a8-43e8-a17a-0f8c8085ce6c)
Right clicking update doesnt restart app in this point instead it ended the process,
After launching it again it works / sometimes asks to relogin

Bug is easily replicated three other systems that i have, All of them have Debian 12 and Xfce installed.

**Comment by Vendicated** [comment] 2023-12-12 11:36
duplicate of #219

**Closed by Vendicated** 2023-12-12 11:36 UTC

**Comment by CelalCaglarOzturk** [comment] 2023-12-12 12:04
its not actually the same, in #219 its mentioned when system is offline.
This computer is 24/7 server connected with cable and issue persists

**Comment by Vendicated** [comment] 2023-12-12 12:05
>>> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.
