### ISSUE TITLE
[Bug] screenshare doesnt work anymore

### ISSUE THREAD

**Issue by thankarezos** [Vencord/Vesktop#601] opened 2024-05-12 18:35 UTC
### Discord Account

thankarezos

### Operating System

EndeavourOS Linux x86_64  Kernel 6.6.30-2-lts

### Linux Only ~ Desktop Environment

Kde Plasma 6.0.4 wayland

### What happens when the bug or crash occurs?

Screenshare doesnt work anymore it just loads like the official discord app. also if I run it from terminal i get this: ``'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()`` not sure if pipewire is the problem here tho
![image](https://github.com/Vencord/Vesktop/assets/25669447/4cbe7aad-98a9-4db6-a623-affabe4081ad)
I tried -bin aur -git aur normal aur and flatpak . all the same. I even tried enabling vesktop to run directly on wayland with 
--enable-features=UseOzonePlatform --ozone-platform-hint=auto

### What is the expected behaviour?

Be able to Screenshare

### How do you recreate this bug or crash?

1. Go into a call 2. Try to share a monitor or an app 3. It just loads forever

### Debug Logs

```
[arRPC > process] started
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-05-12 21:29:50.201] [venmic] [info] [patchbay] (get) running venmic 3.4.2
[2024-05-12 21:29:50.211] [venmic] [info] [patchbay] (handle) found default metadata: 37
[2024-05-12 21:29:50.211] [venmic] [info] [patchbay] (meta_update) speaker name: "alsa_output.usb-Razer_Razer_Nari-00.analog-game"
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-05-12 18:48
![Uploading image.png…]()

**Comment by thankarezos** [comment] 2024-05-12 19:22
@Vendicated  Its not portal problem, I noticed that sharing does work if noone shares when I press the share. if someone else shares this happens. If I share first even if the other persons shares it still works and I can change windows and screens without problem. Yes the workaround is to tell the other person to close the share for a bit, the only reason I did catch it now was because I was the one only sharing all this time. I think you closed the issue too fast because that's no way it's a portal problem because it depends on the other person sharing or not.

**Comment by Vendicated** [comment] 2024-05-12 19:37
oh that's a discord issue, even happens in normal browser

we can probably fix it. anyway your current issue information is outdated then, please update it to reflect your new findings

**Comment by Vendicated** [comment] 2024-05-12 19:37
actually duplicate of https://github.com/Vencord/Vesktop/issues/560 then

**Closed by Vendicated** 2024-05-12 19:37 UTC
Labels: invalid, system issue

**Comment by pixL404** [comment] 2024-06-24 18:45
Hi, this issue should apparently not be closed, as my comment in #560 was marked as off-topic

Screen sharing is not working for me on NixOS (Wayland Session) with the version `1.5.2`

**Comment by Vendicated** [comment] 2024-06-24 18:46
please stop hijacking random unrelated issues. this and the other issue are specifically about being unable to start a stream while already watching someone else's stream, not general inability to stream at all. we do not support nixos.

**Comment by pixL404** [comment] 2024-06-24 18:58
> please stop hijacking random unrelated issues. this and the other issue are specifically about being unable to start a stream while already watching someone else's stream, not general inability to stream at all. we do not support nixos.

thanks for clarifying. NixOS doesn't have to be specifically supported, the program is built from source.
