### ISSUE TITLE
[MacOS] Vesktop extensions and settings not part of regular discord not appearing on Home Screen

### ISSUE THREAD

**Issue by IBtheanimator** [Vencord/Vesktop#596] opened 2024-05-09 15:09 UTC
### Discord Account

ib_studios

### Operating System

MacOS Ventura

### What happens when the bug or crash occurs?

When trying to change added encored plugins I wasn't able to find a encored specific section. I tried restarting and changing versions but it didn't appear. However, it was present a few days ago.
<img width="200" alt="Screenshot 2024-05-09 at 17 03 33" src="https://github.com/Vencord/Vesktop/assets/133630986/05f610b0-1621-4609-8ed9-43847bd8403d">
I thought it was because I needed to update vencord however when clicking the popup to do so I received a blank screen
<img width="503" alt="Screenshot 2024-05-09 at 17 07 07" src="https://github.com/Vencord/Vesktop/assets/133630986/7a8de5ee-dca3-4d82-8da2-f5753ee86d85">
<img width="2043" alt="Screenshot 2024-05-09 at 17 07 19" src="https://github.com/Vencord/Vesktop/assets/133630986/bffc051b-b7d1-4994-81c2-65e25a3d2b22">

### What is the expected behaviour?

I expected to see the vencord specific section that I had seen before

### How do you recreate this bug or crash?

I am not sure how exactly this happened so I can't provide steps for replication

### Debug Logs

```
I don't know how to run desktop on command line .-.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-05-09 15:10
duplicate of 3 million other issues https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+sort%3Aupdated-desc

**Closed by Vendicated** 2024-05-09 15:10 UTC
Labels: bug
