### ISSUE TITLE
[Bug] Sporadic crash on launch.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Vencord/Vesktop#819] opened 2024-08-18 17:37 UTC
### Discord Account

https://discord.com/users/798720532848705576

### Operating System

https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso from https://koji.fedoraproject.org/koji/rpminfo?rpmID=38347230

### Linux Only ~ Desktop Environment

https://kojipkgs.fedoraproject.org//packages/plasma-desktop/6.1.4/1.fc40/x86_64/plasma-desktop-6.1.4-1.fc40.x86_64.rpm from https://koji.fedoraproject.org/koji/rpminfo?rpmID=39683231

### Package Type

```sh
flatpak install 'https://dl.flathub.org/repo/appstream/dev.vencord.Vesktop.flatpakref' && \
flatpak update 'app/dev.vencord.Vesktop/x86_64/stable' --commit=5ef97a0229c851efc97b7562f997e6c37bb0b0e73c107b21dad2246224d4fa32
```

### What happens when the bug or crash occurs?

The application closes, and I see an automatic notification from GNOME ABRT.

### What is the expected behaviour?

Vesktop should open without crashing.

### How do you recreate this bug or crash?

Invoke the `.desktop` file via KDE Plasma 6's *Icons-Only Task Manager*.

### Debug Logs

https://github.com/user-attachments/files/16650533/ccpp-2024-08.zip

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-08-18 19:42
the debug zip you provided contains no useful information since it doesn't seem to have stdout/stderr

in any case this is
1. a likely duplicate of https://github.com/Vencord/Vesktop/issues/803, see my reply there
2. if not 1, an issue with your system you will have to resolve yourself. you can get more help in our support channel

**Closed by Vendicated** 2024-08-18 19:42 UTC
Labels: bug

**Comment by RokeJulianLockhart** [comment] 2024-08-18 20:02
> https://github.com/Vencord/Vesktop/issues/819#issuecomment-2295369005

@Vendicated, the error message that appears in ABRT is indeed identical. However, the problem is significantly less impactful than that report describes – merely invoking the icon again after the notification appears it adequate to have it run. I don't need to quit it or modify any permissions.

Irrespective, why does it differing to that report ensure that it's an issue with my underlying OS? There is, of course, the possibility that it's a problem with Vesktop? After all, Discord doesn't appear to exhibit this behaviour on my system.

**Comment by Vendicated** [comment] 2024-08-18 21:10
1. i have no idea what you're talking about or what ABRT is. you can just run vesktop from terminal and get the console output
2. read my reply to that issue, it will solve your issue.
3. i would advise you to talk more like a human being and using simpler language so other people can better understand you

If you need any further help, use our support channel. GitHub is for tracking actual bugs and features, not support
