### ISSUE TITLE
Vesktop crashes immediately after start on electron 30

### ISSUE THREAD

**Issue by Orest58008** [Vencord/Vesktop#513] opened 2024-04-17 16:36 UTC
**Describe the bug**
Crashes immediately after fox-girl gif start-up screen, no further graphic output is reached

**To Reproduce**
Start Vesktop by any means

**Expected behavior**
Vesktop starting

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): sway
 - Version: Vesktop 1.5.1-1, Arch Linux latest

**Command line output**

```
[56658:0417/193243.581460:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[56658:0417/193243.581508:ERROR:select_file_dialog_linux_portal.cc(286)] Failed to read portal version property
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
zsh: segmentation fault (core dumped)  vesktop
[56705:0100/000000.957125:ERROR:broker_posix.cc(41)] Recvmsg error: Connection reset by peer (104)
```

**Additional context**

**Comment by Cynosphere** [comment] 2024-04-17 16:38
Duplicate of #508 and #509

**Closed** 2024-04-17 16:48 UTC
Labels: bug
