### ISSUE TITLE
[Bug] Vesktop doesn't start after first run

### ISSUE THREAD

**Issue by literon36** [Vencord/Vesktop#587] opened 2024-05-07 05:08 UTC
### Operating System

Debian 12

### Linux Only ~ Desktop Environment

Gnome on Wayland

### What happens when the bug or crash occurs?

On the first run I was able to login and pull my config from the cloud without issues.
Restarting Vesktop results in the shiggy loading screen and the tray icon showing up, but after the loading screen closes, the actual Discord window doesnt show up.

### What is the expected behaviour?

I expect the Discord window to show up after the loading screen.

### How do you recreate this bug or crash?

1. Start Vesktop for the first time (or after a reset)
2. Hit submit on the welcome screen
3. Quit Vesktop
4. Start Vesktop

### Debug Logs

```
$ flatpak run dev.vencord.Vesktop 
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0507/130625.521581:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0507/130626.276009:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0507/130626.276264:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[50:0507/130627.789141:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[50:0507/130627.789458:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[50:0507/130627.789931:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[50:0507/130627.790407:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[50:0507/130627.790584:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[50:0507/130627.790791:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[50:0507/130627.795324:ERROR:shared_image_factory.cc(984)] CreateSharedImage: could not create backing.
[50:0507/130627.795683:ERROR:shared_image_factory.cc(767)] DestroySharedImage: Could not find shared image mailbox
[50:0507/130627.799755:ERROR:gpu_service_impl.cc(1154)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[3:0507/130627.995552:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=8704
[117:0507/130628.655844:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[117:0507/130628.659209:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[117:0507/130628.659537:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[117:0507/130628.659903:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[117:0507/130628.663315:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[117:0507/130628.667286:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[117:0507/130628.667532:ERROR:shared_image_factory.cc(984)] CreateSharedImage: could not create backing.
[117:0507/130628.668649:ERROR:shared_image_factory.cc(767)] DestroySharedImage: Could not find shared image mailbox
[117:0507/130628.668917:ERROR:gpu_service_impl.cc(1154)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[3:0507/130628.730205:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=8704
[135:0507/130629.061807:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[135:0507/130629.061958:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[135:0507/130629.062083:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[135:0507/130629.062221:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[135:0507/130629.062413:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[135:0507/130629.062525:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[135:0507/130629.062604:ERROR:shared_image_factory.cc(984)] CreateSharedImage: could not create backing.
[135:0507/130629.062680:ERROR:shared_image_factory.cc(767)] DestroySharedImage: Could not find shared image mailbox
[135:0507/130629.062822:ERROR:gpu_service_impl.cc(1154)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[3:0507/130629.104781:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=8704
[74:0507/130629.367623:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.

```

The first few errors are fixed by manually allowing access to the dbus interfaces via flatseal, but the rest stays the same.
Trying to reset the application via the icon or deleting the Vesktop folder in `~/.var/app/` and not installing any plugins results in the same situation.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-05-07 10:34
duplicate of various other issues, see those for solution
https://github.com/search?q=repo%3AVencord%2FVesktop+RGBA_8888&type=issues

**Closed by Vendicated** 2024-05-07 10:34 UTC
Labels: bug

**Comment by literon36** [comment] 2024-05-08 01:24
oh thank you! i was searching for duplicates, but apparently with the wrong terms °°'
