### ISSUE TITLE
Crash when resizing to fullscreen.

### ISSUE THREAD

**Issue by FlashAndromeda** [Vencord/Vesktop#542] opened 2024-04-25 00:00 UTC
**Describe the bug**

Whenever I click to fullscreen the vesktop window, it instantly crashes and then keeps crashing upon launching until I delete the vesktop config folder.

**To Reproduce**

1. Open vesktop
2. Click the fullscreen button on the window frame

**Expected behavior**

Vesktop resizes the window to full screen.

**Desktop (please complete the following information):**
 - OS/Distro: EndeavourOS - Arch
 - Desktop Environment (linux only): KDE Plasma
 - Version: 6.8.7

**Command line output**

```
[356958:0425/015801.102491:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.102658:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.102753:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.102854:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.102950:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103001:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103175:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103217:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103291:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103324:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103393:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103425:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103498:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103529:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103595:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103630:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103697:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103729:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103795:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103826:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.103901:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.103932:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104004:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104035:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104109:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104140:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104217:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104249:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104313:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104346:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104417:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104446:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104527:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104564:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104645:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104675:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104749:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104781:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104854:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104886:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.104961:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.104992:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105056:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105089:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105162:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105192:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105260:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105290:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105359:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105388:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105462:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105493:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105566:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105597:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105675:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105709:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105775:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105805:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105871:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105901:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.105968:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.105998:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106067:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106097:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106163:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106207:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106279:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106342:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106411:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106440:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106511:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106540:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106606:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106635:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106713:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106743:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106808:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106838:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[356958:0425/015801.106905:ERROR:gbm_wrapper.cc(72)] Failed to get fd for plane.: No such file or directory (2)
[356958:0425/015801.106936:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[356958:0425/015804.304303:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[356958:0425/015804.320151:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[356958:0425/015804.325128:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

**Additional context**

I'm using dual ultrawide monitors (3440x1440@160Hz for main and 2560x1080@60Khz for side monitor) and GTX1080 for GPU.

**Comment by Cynosphere** [comment] 2024-04-25 00:03
Duplicate of #508

**Closed by Cynosphere** 2024-04-25 00:03 UTC
Labels: bug

**Comment by FlashAndromeda** [comment] 2024-04-25 00:05
Vesktop runs normally for me though, the crash happens only when I try to full screen it.
