### ISSUE TITLE
Vesktop cannot unmute

### ISSUE THREAD

**Issue by Tazi0** [Vencord/Vesktop#458] opened 2024-03-18 10:53 UTC
**Describe the bug**
I cannot unmute and there is no process to give vesktop permission for my mic

**To Reproduce**
1. Open Vesktop
2. Enter a channel
3. Try to unmute

**Expected behavior**
It should unmute or atleast give me an option to give permission

**Screenshots**
![Screenshot 2024-03-18 at 11 52 42](https://github.com/Vencord/Vesktop/assets/45716542/4830f509-90a6-41e7-809f-2159d70a2557)

**Desktop (please complete the following information):**
 - OS/Distro: MacOs
 - Version: 14.0 (23A344)

**Comment by Vendicated** [comment] 2024-03-18 14:01
duplicate of https://github.com/Vencord/Vesktop/issues/440

**Closed by Vendicated** 2024-03-18 14:01 UTC
Labels: duplicate
