### ISSUE TITLE
[Feature Request] Color Profiles Override

### ISSUE THREAD

**Issue by cyrneko** [Vencord/Vesktop#895] opened 2024-10-07 00:10 UTC
### Motivation

Under some specific circumstances, Chromium/Electron may pick an incorrect color space because it thinks e.g SRGB is unsupported. This means that colors may be washed out in the entire client, which makes colors inaccurate and the app less pleasant to look at, especially once you notice it.

Additionally, because there is no other way than passing the `--force-color-space=srgb` commandline argument, there is no way to fix this than running it from the CLI or a custom desktop file. In the case of the Flathub/Flatpak release, editing the existing .desktop file to append `--force-color-space=srgb` to the end of the `exec=` line does not work.

### Solution

A Color Space override in the Vesktop Settings.

This could either be a dropdown of multiple options, e.g `srgb` and `p3` or a simple 'force SRGB' toggle, depends on what may be desired by others which face a similar issue.

### Alternatives

Alternatives include:
- starting Vesktop from the CLI with `--force-color-space=srgb`
  **Issues with this approach:**
  This requires you to know how to use the CLI for your preferred way of installing/using Vesktop, which is information you might not already have. It also requires you to launch a terminal every time you wanna use Vesktop and you may also need to know how to use `disown` to detach it from your Terminal window.
- Editing the `.desktop` file for Vesktop
  **Issues with this approach:**
  This requires you to know where your .desktop file is placed, which in the case of using something like `Gear Lever` or `AppImageLauncher` you might not know. This too makes the assumption of the user knowing this beforehand. It also does not work with Flatpak by simply appending the flag.
- Disabling hardware acceleration:
  **Issues with this approach:**
  As in upstream Electron, this issue can be "resolved" by disabling hardware acceleration in some cases. The circumstances that make this work aren't exactly clear to me, but there also isn't a clear correlation between Discord's HW Accel toggle and colors, so most users will not know of this without looking it up first.

### Additional context

I'm running the Flatpak as published on Flathub.org, on an elementaryOS 8 system with the Nvidia proprietary drivers version 550.107.02. This only happens when running an X11 session.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment] 2024-10-07 00:20
this seems like a very hacky solution to a problem that's likely caused by a system misconfiguration and incredibly niche ~ you're the first person I've ever seen complain about this and until now I didn't even know this was a thing

i assume if one is affected by this issue, it will occur in all chromium / electron apps. so fixing it globally in your system would be much more logical, no?

have you tried the following? https://askubuntu.com/a/1323494

in any case, this is definitely out of scope for vesktop due to being way too niche and specific; we could find dozens of minor things like this where some people would find a switch convenient, but 99.99% of users will never need this. if one needs this, the best solution would be just passing the command line flag, like you mentioned

**Closed by Vendicated** 2024-10-07 00:20 UTC
Labels: enhancement

**Comment by cyrneko** [comment] 2024-10-07 01:47
> this seems like a very hacky solution to a problem that's likely caused by a system misconfiguration and incredibly niche ~ you're the first person I've ever seen complain about this and until now I didn't even know this was a thing
> 
> i assume if one is affected by this issue, it will occur in all chromium / electron apps. so fixing it globally in your system would be much more logical, no?
> 
> have you tried the following? https://askubuntu.com/a/1323494
> 
> in any case, this is definitely out of scope for vesktop due to being way too niche and specific; we could find dozens of minor things like this where some people would find a switch convenient, but 99.99% of users will never need this. if one needs this, the best solution would be just passing the command line flag, like you mentioned

Thanks for the reply! This was the default configuration I got out of the box with the latest elementaryOS 8 RC, and it only occured to Vesktop (I cross-verified with ungoogled chromium and Element), so I thought this issue (for one reason or another) only affected Vesktop

Also thanks for the pointer to that askubuntu answer...for some reason I did not find that anywhere in the searches I did to try and fix this problem, probably because of wrong keywords, so I appreciate you leading me there

All in all that makes sense, have a nice day! :3
