### ISSUE TITLE
Vesktop manipulates system microphone volume during voice call  

### ISSUE THREAD

**Issue by lyfja** [Vencord/Vesktop#467] opened 2024-03-24 18:50 UTC
**Describe the bug**

Whenever I am in a voice call and speak, Vesktop manipulates my system's microphone volume seemingly at random. I always keep it at 40%, but Vesktop seems to just change it to random values. This is particularly annoying for my friends since to them I randomly get louder or quiter ever so often.

**To Reproduce**

1. Join a voice call/voice channel
2. Talk (From my observations this bug would only start to occur once I talk, if I stay silent or muted nothing happens)
3. Observe your system microphone volume changing at random points in time

**Expected behavior**

System microphone volume should remain unchanged by Vesktop

**Desktop (please complete the following information):**
 - OS/Distro: Bazzite 39 (based on Fedora Kinoite 39)
 - Desktop Environment (linux only): KDE Plasma 5.27
 
 Vesktop version: canary 278149 (a4658b1) Host 0.0.323 x64 Linux 64-bit (6.7.9-204.fsync.fc39.x86_64)

**Comment by Vendicated** [comment] 2024-03-24 18:54
duplicate of https://github.com/Vencord/Vesktop/issues/161

**Closed by Vendicated** 2024-03-24 18:54 UTC
Labels: bug
