### ISSUE TITLE
Vanishing tray icon until Vesktop restart

### ISSUE THREAD

**Issue by Plarpoon** [Vencord/Vesktop#274] opened 2023-12-05 17:19 UTC
Host details: KDE 5.28.8 with kernel 6.5.0-14 Kubuntu.

Flatpak installation type.

Vesktop details:
Stable 250836 (84e28a2)
Vencord 6573c47 (Vesktop V0.4.4)
Electron 27.1.2
Chromium 118.0.5993.144
Linux 64-Bit

_**Sometimes the Vesktop tray icon disappears, this bug was present both when I was using the .DEB version of the program and even now that I am using the Flatpak one.**_

![Screenshot_20231205_181142](https://github.com/Vencord/Vesktop/assets/40299833/3040513e-81e2-4afe-8084-99a9f7046d25)

**Found workaround:** In the "Vencord" settings tab  you will find a "Restart Client" button. Pressing it it's the only possible way to restore the tray icon.

**Comment by Plarpoon** [comment] 2023-12-05 17:42
Attention to all Flatpak users wanting to use the workaround, read #275

**Comment by Vendicated** [comment] 2023-12-28 02:48
i have never experienced this in months of using it on windows and gnome (fedora)

potentially a kde issue?

in any case this is basically impossible to debug (since i can't reproduce) and there's likely nothing we can do anyway, since if it doesn't work consistently, there's an issue with the underlying implementation, sorry!

thus i'll be closing this as wontfix

**Closed by Vendicated** 2023-12-28 02:48 UTC
