### ISSUE TITLE
The client freezes when starting screen share after enabling pipewire

### ISSUE THREAD

**Issue by wayhoi** [Vencord/Vesktop#471] opened 2024-03-27 13:37 UTC
**Describe the bug**

After changing pulseaudio to pipewire, starting screen share freezes the client.

**To Reproduce**

1. Install Linux Mint 21.3.
2. Enable Pipewire.
3. Start the client.
4. Start streaming.

**Expected behavior**

The application continues to work.

**Screenshots**

![Screenshot from 2024-03-27 16-25-53](https://github.com/Vencord/Vesktop/assets/163326927/93ce0f57-bbe6-4b23-9708-639b0aa724fd)

**Desktop (please complete the following information):**

![Screenshot from 2024-03-27 16-23-13](https://github.com/Vencord/Vesktop/assets/163326927/568f7771-ab1d-4177-9f38-9043e72932d8)

```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 426
Tile Size: 65472
User Name: sedyh
Host Name: sedyh-pc
Server Name: PulseAudio (on PipeWire 0.3.48)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1f.3.analog-stereo
Default Source: alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie: dca1:1bd6
```

**Command line output**

```
/opt/Vesktop/vesktop
[8698:0327/163219.611204:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
[2024-03-27 16:32:31.380] [venmic] [info] [patchbay] (get) running venmic 3.3.2
```

**Comment by Vendicated** [comment] 2024-03-27 13:40
duplicate of https://github.com/Vencord/venmic/issues/18

**Closed by Vendicated** 2024-03-27 13:40 UTC
Labels: bug
