### ISSUE TITLE
No screensharing with audio possible / Bad audio when watching shared screens

### ISSUE THREAD

**Issue by S3nsh1r0** [Vencord/Vesktop#888] opened 2024-10-03 10:30 UTC
### Discord Account

senshiro.2187

### Operating System

Windows 10 (ReviOS 23.12)

### Package Type

exe

### What happens when the bug or crash occurs?

When I wanted to share my screen with sounds it just doesnt share my screen at all. When I watched  a shared screen with audio there are frequently "flickering" noises that hurt in the ears. It is good to mention that the plugin for nitro settings arent changing anything, so the Bug would also occur when using the non-nitro settings.

### What is the expected behaviour?

I expected that I just go in a call, click on the screenshare button, enable "with audio" and it would just work fine, like it did some weeks before

### How do you recreate this bug or crash?

1. open Vesktop
2. go in a call (can be either alone or with someone)
3. click on the screensharing option
4. enable the audio before start streaming the screen

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by NekoAlosama** [comment] 2024-10-03 13:34
Duplicate of #334 . I'm not a maintainer, I'm also waiting for a fix.

**Closed** 2024-10-03 14:21 UTC
Labels: bug
