### ISSUE TITLE
Add support for custom app icons

### ISSUE THREAD

**Issue by kubajznicek** [Vencord/Vesktop#426] opened 2024-03-07 15:15 UTC
I would like to have the app icon to be same as Discord's icon. I tried to find in in the source code myself but i didn't succeed.

Maybe if there was an option to upload your own icon for the app to use.
I have no idea how hard it may be to implement, it isn't a app breaking bug so I understand if you don't want to spend amounts of time to implements this.

**Comment by cheesesamwich** [comment] 2024-03-07 15:16
the world just see shiggy at all costs

**Comment by cheesesamwich** [comment] 2024-03-07 15:22
homophobia

cancelled!11!11!11!

**Comment by kubajznicek** [comment] 2024-03-07 15:28
So I guess issue closed ?

**Comment by TheKodeToad** [comment] 2024-03-07 15:28
Doesn't Windows let you do this with the properties dialog?

**Comment by kubajznicek** [comment] 2024-03-07 15:30
I am on Ubuntu

> Doesn't Windows let you do this with the properties dialog?

**Comment by Vendicated** [comment] 2024-03-07 15:34
you can change the desktop icon yourself

**Comment by Vendicated** [comment] 2024-03-07 15:35
dupe of #401

**Closed by Vendicated** 2024-03-07 15:35 UTC
Labels: enhancement

**Comment by Nocty1501** [comment] 2024-03-15 16:16
I was able to do this on Arch running KDE Plasma by changing the icon of the `.desktop` file, however I could not find an obvious way to change the notification icon (which, as the main Vesktop icon, scans terribly).

**Comment by cootshk** [comment] 2024-05-05 03:49
How about the taskbar and app icon?
