### ISSUE TITLE
[Bug] Vesktop stuck at "Loading Vesktop"

### ISSUE THREAD

**Issue by the-zphr** [Vencord/Vesktop#673] opened 2024-06-19 17:01 UTC
### Discord Account

the_zphr

### Operating System

Windows 11

### What happens when the bug or crash occurs?

It happens when launching Vesktop, doesnt do anything besides showing "Loading Vesktop"

### What is the expected behaviour?

Expect to normally launch

### How do you recreate this bug or crash?

Install Vesktop (Installer)
Launch Vesktop
Shows "Loading Vesktop"
End

Install Vesktop (Portable)
Launch Vesktop
Shows "Loading Vesktop"
End

Install Vesktop (Scoop)
Launch Vesktop
Shows "Loading Vesktop"
End

### Debug Logs

```
No logs file found
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by the-zphr** [comment] 2024-06-19 17:13
Where can i find it? I tried looking in install folder - no results

**Comment by Vendicated** [comment] 2024-06-19 17:15
![image](https://github.com/Vencord/Vesktop/assets/45497981/5999b856-fdcb-4390-b017-a3fe32422b27)

go to `%LOCALAPPDATA%/Vesktop` and run `Vesktop.exe` from a terminal

**Comment by the-zphr** [comment] 2024-06-19 17:16
Got this, nothing else
![image](https://github.com/Vencord/Vesktop/assets/80064625/4caf613c-ad43-48f1-971d-976df61d4b72)

**Comment by happyendermangit** [comment] 2024-06-19 21:12
Same issue for me, i got this on my linux terminal (running kubuntu)
```
happyenderman  ~/     v21.0.3   v21.7.1  ♥ 22:10  vesktop 
(node:56612) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/happyenderman/.config/vesktop/vencordDist/vencordDesktopMain.js from /opt/Vesktop/resources/app.asar/dist/js/main.js not supported.
vencordDesktopMain.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename vencordDesktopMain.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/happyenderman/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at c._load (node:electron/js2c/node_init:2:13672)
    at VCDMain:15:4656
    at VCDMain:1:1022
    at ke (VCDMain:15:4161)
(Use `vesktop --trace-warnings ...` to show where the warning was created)
(node:56612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by Vendicated** [comment] 2024-06-19 21:47
duplicate of #512.

**Closed by Vendicated** 2024-06-19 21:47 UTC
Labels: bug, invalid

**Comment by Nick2bad4u** [comment] 2026-05-06 20:08
This happened to me today, spent a while trying to fix it before I launched from terminal and that fixed it, so the icon shortcut works again.

Any idea why that happens?
