### ISSUE TITLE
[Bug] Vesktop Will Not Auto Log in on Fedora 40

### ISSUE THREAD

**Issue by jfish871** [Vencord/Vesktop#634] opened 2024-05-31 16:00 UTC
### Discord Account

trog_troginson

### Operating System

Fedora 40 Workstation

### Linux Only ~ Desktop Environment

Gnome On Wayland

### What happens when the bug or crash occurs?

Any time totally shutdown and reboot the app discord will state that I must log in again. I must go through the full email / password / 2 FA system every time I start the app. Doing the QR code does not work. I have tried both the flatpak and the RPM versions, currently running the RPM and they both have the same issue. For some reason Running Vesktop from the command line resolves this issue. After launching the app from the command line once, the issue is totally resolved.

### What is the expected behaviour?

I start vesktop and it just logs me in and puts me on the friends page

### How do you recreate this bug or crash?

Have a computer running Fedora 40 workstation, with the Gnome desktop on wayland. Make sure vesktop is not running, start vesktop from the app icon.

### Debug Logs

```
trogtroginson@trog-station-pro:~$ vesktop
[14283:0531/085657.391031:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[14283:0531/085659.925980:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[14283:0531/085711.704829:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-05-31 16:03
duplicate of various other issues.  https://github.com/Vencord/Vesktop/issues/375#issuecomment-1925395338

**Closed by Vendicated** 2024-05-31 16:03 UTC
Labels: bug
