### ISSUE TITLE
[Bug] zsh: trace trap (core dumped)  vesktop

### ISSUE THREAD

**Issue by aljustiet** [Vencord/Vesktop#1026] opened 2024-12-27 16:58 UTC
### Discord Account

aljustiet

### Operating System

Arch

### Linux Only ~ Desktop Environment

Hyprland

### Package Type

AppImage/AUR

### What happens when the bug or crash occurs?

It doesn't launch
AppImage installed using [AppMan](https://github.com/ivan-hc/AppMan) and [AUR](https://aur.archlinux.org/packages/vesktop) package
Launchs with flatpak package.

### What is the expected behaviour?

Core not to be dumped

### How do you recreate this bug or crash?

1. Install AppImage on Arch
2. Run AppImage

### Debug Logs

```
❯ gdb ./vesktop
GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./vesktop...
(No debugging symbols found in ./vesktop)
(gdb) run
Starting program: /home/aljustiet/Applications/vesktop/vesktop 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 40493]
process 40490 is executing new program: /usr/bin/bash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
process 40490 is executing new program: /usr/bin/env
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
process 40490 is executing new program: /usr/bin/bash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 40498]
[Detaching after fork from child process 40500]
process 40490 is executing new program: /tmp/.mount_vesktoyQlXhF/vesktop.bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1dff6c0 (LWP 40510)]
[Detaching after fork from child process 40511]
[Detaching after fork from child process 40512]
[Detaching after fork from child process 40513]
[New Thread 0x7ffff15fe6c0 (LWP 40516)]
[New Thread 0x7ffff0dfd6c0 (LWP 40517)]
[New Thread 0x7ffff05fc6c0 (LWP 40518)]
[New Thread 0x7fffefdfb6c0 (LWP 40519)]
[New Thread 0x7fffef5fa6c0 (LWP 40520)]
[New Thread 0x7fffeedf96c0 (LWP 40521)]
[New Thread 0x7fffee5f86c0 (LWP 40522)]
[New Thread 0x7fffe31ff6c0 (LWP 40523)]
[New Thread 0x7fffe28bd6c0 (LWP 40524)]
[New Thread 0x7fffe20bc6c0 (LWP 40525)]
[New Thread 0x7fffe18bb6c0 (LWP 40526)]
[New Thread 0x7fffe0cba6c0 (LWP 40527)]
[New Thread 0x7fffe04b96c0 (LWP 40528)]
[New Thread 0x7fffdfcb86c0 (LWP 40529)]
[Thread 0x7fffe20bc6c0 (LWP 40525) exited]
[Thread 0x7fffe18bb6c0 (LWP 40526) exited]
[Thread 0x7fffe0cba6c0 (LWP 40527) exited]
[Thread 0x7fffe04b96c0 (LWP 40528) exited]
[Thread 0x7fffdfcb86c0 (LWP 40529) exited]
[Thread 0x7fffe28bd6c0 (LWP 40524) exited]
[Thread 0x7fffe31ff6c0 (LWP 40523) exited]
[New Thread 0x7fffe31ff6c0 (LWP 40530)]
[New Thread 0x7fffe28bd6c0 (LWP 40531)]
[New Thread 0x7fffdfcb86c0 (LWP 40532)]
[New Thread 0x7fffe04b96c0 (LWP 40533)]
[New Thread 0x7ffff7fb66c0 (LWP 40534)]
[New Thread 0x7fffeddf76c0 (LWP 40535)]
[New Thread 0x7fffed5f66c0 (LWP 40536)]
[New Thread 0x7fffecdf56c0 (LWP 40537)]
[New Thread 0x7fffec5f46c0 (LWP 40538)]
Checking for update
[New Thread 0x7fffebdf36c0 (LWP 40539)]
[New Thread 0x7fffe20bc6c0 (LWP 40540)]
[New Thread 0x7fffe18bb6c0 (LWP 40541)]
[New Thread 0x7fffe10ba6c0 (LWP 40542)]
[New Thread 0x7fff634af6c0 (LWP 40543)]
[New Thread 0x7fff62cae6c0 (LWP 40544)]
[New Thread 0x7ffff4d636c0 (LWP 40545)]
[New Thread 0x7fff615fe6c0 (LWP 40547)]
[New Thread 0x7fff61dff6c0 (LWP 40546)]
[New Thread 0x7fff60dfd6c0 (LWP 40548)]
[New Thread 0x7fff605fc6c0 (LWP 40549)]
[New Thread 0x7fff5fdfb6c0 (LWP 40550)]
[40490:1227/215421.214362:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[40490:1227/215421.214409:ERROR:select_file_dialog_linux_portal.cc(294)] Failed to read portal version property
[New Thread 0x7fff5f5fa6c0 (LWP 40551)]
[New Thread 0x7fff5edf96c0 (LWP 40552)]
[New Thread 0x7fff5e5f86c0 (LWP 40554)]
[New Thread 0x7fff5ddf76c0 (LWP 40555)]
[New Thread 0x7fff5d5f66c0 (LWP 40556)]
[New Thread 0x7fff5cdf56c0 (LWP 40557)]
[Detaching after fork from child process 40559]
[New Thread 0x7fff5c3e36c0 (LWP 40560)]
[New Thread 0x7fff5b76b6c0 (LWP 40568)]
[Detaching after fork from child process 40574]
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
[Detaching after fork from child process 40684]
[New Thread 0x7fff57f346c0 (LWP 40693)]
[Thread 0x7fff57f346c0 (LWP 40693) exited]
[Detaching after fork from child process 40707]
[Detaching after fork from child process 40708]
[Detaching after fork from child process 40720]

Thread 1 "vesktop.bin" received signal SIGTRAP, Trace/breakpoint trap.
0x000055555868a326 in ?? ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 40490] will be killed.

Quit anyway? (y or n) y

warning: BFD: reopening /tmp/.mount_vesktoyQlXhF/vesktop.bin: No such file or directory
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-12-27 21:30
duplicate of https://github.com/Vencord/Vesktop/issues/1022

**Closed by Vendicated** 2024-12-27 21:30 UTC
Labels: bug

**Comment by aljustiet** [comment] 2024-12-28 04:10
> duplicate of #1022

But, my portal is running fine. Can I run vesktop in debug mode, and examine what's happening?
