### ISSUE TITLE
[Bug] flatpak v1.5.3 fails to run (Wayland, NVIDIA)

### ISSUE THREAD

**Issue by fuchs-fabian** [Vencord/Vesktop#1008] opened 2024-12-15 11:31 UTC
### Operating System

Fedora Linux 41 (Workstation Edition)

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The crash occurs when starting Vesktop

### What is the expected behaviour?

Should start Vesktop

### How do you recreate this bug or crash?

See this issue also: https://github.com/flathub/dev.vencord.Vesktop/issues/40

- OS Name: Fedora Linux 41 (Workstation Edition)
- GNOME Version: 47
- Windowing System: Wayland
- NVIDIA Linux Graphics Driver: v565.77

Install flatpak using

```sh
flatpak install flathub dev.vencord.Vesktop
```

Starting Vesktop...

### Debug Logs

```
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto --enable-wayland-ime
[3:1215/121027.208922:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:1215/121027.388094:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1215/121027.388130:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(node:3) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ff/.var/app/dev.vencord.Vesktop/config/vesktop/settings/quickCss.css'
    at async open (node:internal/fs/promises:639:25)
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[3:1215/121027.522334:ERROR:wayland_event_watcher.cc(47)] libwayland: [destroyed object]: error 7: failed to import supplied dmabufs: Could not bind the given EGLImage to a CoglTexture2D

/app/bin/startvesktop: line 27:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-12-15 11:54
duplicate of https://github.com/Vencord/Vesktop/issues/1003.

**Closed by Vendicated** 2024-12-15 11:54 UTC
Labels: bug

**Comment by fuchs-fabian** [comment] 2024-12-15 13:15
Thanks for the tip. I didn't expect it to be the system. After a bit of research, I then had the concrete solution:

https://github.com/Vencord/Vesktop/issues/1003#issuecomment-2543869913
