### ISSUE TITLE
Enable native Wayland support

### ISSUE THREAD

**Issue by TheSilverFoxes** [Vencord/Vesktop#550] opened 2024-04-29 08:45 UTC
I'm on Fedora 40 with GNOME, is there a way to enable Wayland support through the settings without having to run Vesktop with ` --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland ` flag?
Thank you.

**Comment by Vendicated** [comment] 2024-04-29 08:47
no, and all of these flags are obsolete, just use `--ozone-platform-hint=auto`

duplicate of #342

**Closed by Vendicated** 2024-04-29 08:47 UTC
