### ISSUE TITLE
Window size is not remembered

### ISSUE THREAD

**Issue by Quriz** [Vencord/Vesktop#501] opened 2024-04-12 19:49 UTC
**Describe the bug**
When opening Vesktop, the previous window size is not remembered. It opens in the right position, just not the right size.

**To Reproduce**
Close Vesktop and open it again.

**Expected behavior**
Vesktop should remember the previous window size.

**Desktop:**
OS: Windows 10

**Additional context**
I installed it using Scoop.

**Comment by Vendicated** [comment] 2024-06-01 18:05
it's working as intended for everyone else so i assume this is an issue with your system / your window manager

i'll be closing as wontfix for that reason, but if you provide more info about your setup, someone may be able to help

**Closed by Vendicated** 2024-06-01 18:05 UTC
Labels: bug
