### ISSUE TITLE
Endless error popups when vencord update fails

### ISSUE THREAD

**Issue by FrzMtrsprt** [Vencord/Vesktop#361] opened 2024-01-25 03:54 UTC
**Describe the bug**
An error popup dialog is raised when updating vencord has failed due to GitHub being unreachable.  
After closing the popup, another appears, this keeps going on and on.  
This also happens on startup when the user has auto updating vencord enabled.  
Meanwhile, nothing appears in the console.

**To Reproduce**
1. Somehow make GitHub unreachable
2. Go to Updater in settings, and click "Check for Updates"
3. When pending updates appear, click "Update Now"
4. The error dialog appears
5. Try to dismiss the dialog, another appears instantly

**Expected behavior**
A themed dialog appears only once, explaining the failure reason instead of the uncaught exception.

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/15852717/e688cc0c-a63c-4de1-a373-9062dfc78d22)

**Desktop (please complete the following information):**
 - OS/Distro: Windows
 - Desktop Environment (linux only): N/A
 - Version: 11

**Additional context**

What's more, the updater does not follow the system proxy. It'd be better if it does.

**Comment by Vendicated** [comment] 2024-01-25 03:55
dupe of https://github.com/Vencord/Vesktop/issues/219

**Closed by Vendicated** 2024-01-25 03:55 UTC
Labels: bug
