### ISSUE TITLE
Mic volume fluctuates in test mode

### ISSUE THREAD

**Issue by tmvkrpxl0** [Vencord/Vesktop#566] opened 2024-05-02 15:59 UTC
**Describe the bug**

When I self-test my microphone in settings, volume constantly fluctuates.
**To Reproduce**

**Expected behavior**
I expected my voice to sound fine, especially the "sound bar" below shows normal reading when I'm not listening to my own voice. However If I start self test, the bar also fluctuates as well.

**Screenshots**

https://github.com/Vencord/Vesktop/assets/41675181/c19591db-6ffa-4f3d-aad5-a171f007f739

**Desktop (please complete the following information):**
 - OS/Distro: KDE Neon
 - Desktop Environment (linux only): KDE
 - Version: 22.04

**Command line output**

```
$ flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop --disable-gp-enable-features=Uu --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
Using NVIDIA on Wayland, disabling gpu sandbox
Passing the following arguments to Electron: --ozone-platform-hint=auto --disable-gpu-sandbox
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

**Additional context**
My friends say my voice is really hard to hear. but it's fine on google meets. Could this be relevant?
Also same thing happens to official discord web app as well.

**Comment by m2neral** [comment] 2024-05-10 03:40
I had this issue on web and client versions on both windows and linux since 2015. That thing never worked the way it's supposed to for me.

**Comment by Vendicated** [comment] 2024-06-19 17:18
duplicate of #161

**Closed by Vendicated** 2024-06-19 17:18 UTC
Labels: bug
