### ISSUE TITLE
[Bug] <Changing profile picture causes mega lag>

### ISSUE THREAD

**Issue by TheGreenGodTGG** [Vencord/Vesktop#930] opened 2024-10-26 11:13 UTC
### Discord Account

Fartleks

### Operating System

Windows 10

### Package Type

Setup exe

### What happens when the bug or crash occurs?

Whenever i change my profile picture it takes up to 15 seconds to load, freezes and then when it finished freezing all the animations slow down including the save option which takes arround 5 seconds to process

### What is the expected behaviour?

I expect it to quickly change the avatar without slowdown or freezes

### How do you recreate this bug or crash?

1. go to settings
2. click on profiles
3. click change avatar

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment] 2024-10-26 11:27
I can reproduce on my main but can't reproduce on an alt with every single plugin enabled. So unsure what causes this

**Comment by Vendicated** [comment] 2024-10-26 11:40
i tested all plugins with binary search and it seems to be ThemeAttributes. Does disabling it fix it for you?

**Comment by Vendicated** [comment] 2024-10-26 11:48
fixed via https://github.com/Vendicated/Vencord/commit/e7e298d2e7fbdcd9c692dd4a2762951f2f541cdb

**Closed by Vendicated** 2024-10-26 11:48 UTC
Labels: bug
